production:
  production_environment: true
  required_contexts: ["deliverybot/promotion"]
  environment: production

staging:
  auto_deploy_on: refs/heads/staging
  environment: staging

development:
  environment: development
  payload:
    branch: master
    version: 0.0.1

github-test:
  environment: development
  payload:
    branch: master
    version: 0.0.1
