name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Update Deliverybot Status - Pending
      uses: deliverybot/deployment-status@v1.1.1
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set variables
      uses: actions/github-script@0.5.0
      id: vars
      with:
        script: |
          return context.payload.deployment.payload;

    - name: Echo json
      run: |
        echo "${{ steps.vars.outputs.result }}" | jq '.'
        
    - name: Update Deliverybot Status - Success
      if: success()
      uses: 'deliverybot/deployment-status@v1.1.1'
      with:
        state: 'success'
        token: '${{ github.token }}'

    - name: Update Deliverybot Status - Failure
      if: failure()
      uses: 'deliverybot/deployment-status@v1.1.1'
      with:
        state: 'failure'
        token: '${{ github.token }}'