name: 'Deploy'
on: ['deployment']

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Update Deliverybot Status - Pending
      uses: deliverybot/deployment-status@v1.1.1
      with:
        state: 'pending'
        token: '${{ github.token }}'

    - name: 'Checkout'
      uses: 'actions/checkout@v2'
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get deployment event
      uses: actions/github-script@0.5.0
      id: script
      with:
        script: |
          return context.payload.deployment;

    - name: Set variables
      id: vars
      shell: bash
      env:
        deployment: '${{ steps.script.outputs.result }}'
      run: |
        branch=$(echo '$deployment' | jq '.payload.branch')
        environment=$(echo '$deployment' | jq '.payload.target')
        deploymentId=$(echo '$deployment' | jq '.id')
        echo "::set-output name=branch::$branch"
        echo "::set-output name=environment::$environment"
        echo "::set-output name=deployment-id::$deploymentId"
        
    - name: Update Deliverybot Status - Success
      if: success()
      uses: 'deliverybot/deployment-status@v1.1.1'
      with:
        state: 'success'
        token: '${{ github.token }}'

    - name: Update Deliverybot Status - Failure
      if: failure()
      uses: 'deliverybot/deployment-status@v1.1.1'
      with:
        state: 'failure'
        token: '${{ github.token }}'