name: Run
on: push

jobs:
  git:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: List tags
      run: git tag

    - name: Get latest tag
      run: git describe --tags `git rev-list --tags --max-count=1`

    - name: Get branch for SHA
      run: git name-rev --name-only --exclude=tags/* ${{ github.sha }}

  # shellops:
  #   runs-on: ubuntu-latest
  #   steps:

  #   - shell: bash
  #     run: echo $GITHUB_REF

  #   - shell: bash
  #     run: echo ${GITHUB_REF:10}

  #   - shell: bash
  #     run: echo ${GITHUB_REF#refs/*/}

  #   - name: Extract Branch Name
  #     id: extract-branch
  #     shell: bash
  #     run: echo "::set-output name=branch::${GITHUB_REF#refs/*/}"

  #   - name:  ${{ github.repository }}
  #     id: lower
  #     shell: bash
  #     run: |
  #       echo "docker.pkg.github.com/${{ github.repository }}/${GITHUB_REF#refs/*/}" | tr '[:upper:]' '[:lower:]'
  #       echo "::set-output name=branch::docker.pkg.github.com/${{ github.repository }}/${GITHUB_REF#refs/*/}"